### ISSUE TITLE
Significance of motif over background

### ISSUE THREAD

**Issue by hayleymc** [agartland/seqlogo#4]
Hi,

Thanks for a great package!

I just wanted to ask whether palmotif is capable of reporting a statistic similar to the chi-square value as implemented in the 'find_motif' function in tcrdist2?

Thank you,
Hayley

**Comment by agartland** [comment]
Hi Hayley, thanks and glad you're using it! No, we haven't revisited that statistic for a while now. There are a few statistics in `palmotif/compute_logo.py` that  attempt to quantify how surprising the relative logo plot is. The KL divergence statistic or the multinomial log-likelihood are both reasonable. But as with the chi_square test of the former tcrdist, it's important to know how surprising is surprising enough that we should call it "significant". For this I suggest using either a bootstrap of your data (code in compute_logo.py) or a permutation test of some kind. For example, with a permutation test you want to generate your statistic of interest from a simulated null distribution (e.g., sequences or participants with a shuffled label), and then see whether the statistic you actually observed is more extreme than 95% of your null distribution. The tricky part is thinking of the most relevant way to generate that null distribution. All best,
Andrew

**Comment by hayleymc** [comment]
Thanks very much for your reply Andrew, greatly appreciated!
